### PR TITLE
bike.txt added

### PR DESCRIPTION
**Pull request by Coderexist**

### CODE REVIEW

**Comment by LavkushYdv** [comment]
Please add some more bike into it

**Comment by Coderexist** [comment]
Ok I will add some more thanks

**Comment by LavkushYdv** [comment]
Best of luck and will check it again once you have done

**Comment by Coderexist** [comment]
yeah sure

**Review by Coderexist — COMMENTED** [review]
Please have a look

**Review by LavkushYdv — COMMENTED** [review]
Added few which are not bike

**Comment by Coderexist** [comment]
Oh Sorry sorry I will do it again no worry
please have some patience 
thanks for teliing

**Comment by LavkushYdv** [comment]
yup

**Comment by LavkushYdv** [comment]
I am gonna merge it

**Comment by LavkushYdv** [comment]
please add some more file like you know..

**Comment by Coderexist** [comment]
ok

**Pull request merged**
